### ISSUE TITLE
Responce always fail

### ISSUE THREAD

**Issue by Dmo3** [medzaksdn/ZkLib#1]
Hi ,

The result always fail for the most functions ,only getDate is return informations .

```
$host = "192.168.1.5";
$zklib = new ZkLib($host);
print_r( $zklib->unlock() );
```
> SimpleXMLElement Object ( [Row] => SimpleXMLElement Object ( [Result] => 0 [Information] => Fail! ) )

`print_r( $zklib->getDate() );`

> stdClass Object ( [Date] => 2016-12-05 [Time] => 12:49:41 )

also 
`print_r( $zklib->checkState($host) );` 

> 1

my device used (ZEM800) 
any idea?

**Comment by Dmo3** [comment]
fixed ,, there is a password in the device , i just remove it .

if I want to use the password is there a function to set it ?

**Comment by zksdn** [comment]
Sorry, there is no a function to set password ! But to secure the data in the attendance machine you can configure your network so that only the server that contains the application can communicate with the attendance machines !
